---
- name: Web server setup on slave nodes
  hosts: all
  become: yes
  tasks:

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest
    
    - name: Copy index.html to web root
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    
    - name: Copy apache2.conf to Apache config directory
      ansible.builtin.copy:
        src: apache2.conf
        dest: /etc/apache2.conf
        owner: root
        group: root
        mode: '0644'
    
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted