---
- name: Install Java
  ansible.builtin.apt:
    name: default-jdk
    state: present
    update_cache: yes

- name: Print Java installation message
  ansible.builtin.debug:
    msg: "Java installed on Apache group node {{ inventory_hostname }}"
