---
- name: Web server setup on slave nodes
  hosts: all
  become: yes
  tasks:

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: Write nginx status to /tmp/sw_status.txt
      ansible.builtin.copy:
        content: "nginx installed successfully!!\n"
        dest: /tmp/sw_status.txt

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Append apache status to /tmp/sw_status.txt
      ansible.builtin.lineinfile:
        path: /tmp/sw_status.txt
        line: "apache installed successfully!!"
        create: yes
        insertafter: EOF

    - name: Stop nginx service
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: Start httpd on RHEL/CentOS if nginx is stopped
      ansible.builtin.service:
        name: httpd
        state: started
      when:
        - ansible_facts['os_family'] == 'RedHat'
        - "'nginx' not in ansible_facts.services or ansible_facts.services['nginx'].state != 'running'"
